### ISSUE TITLE
Listing?

### ISSUE THREAD

**Issue by jacob0719** [esripdx/ep_padlist#2]
Hey,
Just installed the plug-in and I like it!  However, when I went to my list page, the URL isn't including the /p/<pad title>

Just thought I'd let you know.

**Comment by e4r7hbug** [comment]
It might be best to close this issue as #3 has the proposed fix.

**Comment by patricktokeeffe** [comment]
Frustrating to see this broken, stale version is what's hosted on npmjs. I think it's better than the `list_pads` EP plugin (or would be if it worked out of the box). 

At least for Windows EP installs, the quickest fix is to install the plugin, then open `<ep-install-dir>/node_modules/ep_padlist/templates/pads.html` and add `/p`:

``` diff
  <ul>
    <% pads.forEach(function(pad){ %>
-      <li><a href="/<%= pad.toString() %>"><%= pad.toString() %></a></li>
+      <li><a href="/p/<%= pad.toString() %>"><%= pad.toString() %></a></li>
    <% }) %>
  </ul>
```

**Comment by pht31337** [comment]
https://github.com/Piotr-Pht-Jasiek/ep_padlist/tree/patch-1 
patched

**Comment by myrdd** [comment]
My workaround ansible task for the [`debops.etherpad`](https://docs.debops.org/en/latest/ansible/roles/debops.etherpad/index.html) ansible role:

```
- name: fix ep_padlist
  lineinfile:
    line: '      <li><a href="/p/<%= pad.toString() %>"><%= pad.toString() %></a></li>'
    regexp: '^      <li><a href="/'
    path: '{{ etherpad_home + "/" + etherpad_repository }}/node_modules/ep_padlist/templates/pads.html'
```

Does anyone know how unmaintained packages are handled (or „can be handled“) in npm?
